### ISSUE TITLE
Action manifest not found

### ISSUE THREAD

**Issue by lucsdjango** [KitwareMedical/SlicerVirtualReality#115]
SteamVR displays an error message in the headset, that "the action manifest for SlicerApp-real was not found", despite json files copied to both directories
Slicer 5.3.0-2023-05-30\slicer.org\Extensions-31771\SlicerVirtualReality\share\vr_actions\
and
Slicer 5.3.0-2023-05-30\

No controller input seems to be working.
Tested with version dec1acf (2023-05-31) and Slicer3D version 5.3.0-2023-05-30 r31771 / 99eb780

Screenshot:
![bug_slicerVr](https://github.com/KitwareMedical/SlicerVirtualReality/assets/18015574/2f218f42-b45d-4709-a83b-ee4c24216eeb)

**Comment by cpinter** [comment]
I built the latest SlicerVR with the latest Slicer, and I cannot get the manifests to work at all, no matter where I copy it. For the record I tried copying it to `Slicer-build`, `Slicer-build\bin\Release`, `SlicerVirtualReality_R\vtkRenderingOpenVR-build` (this is what the error message shows, with a twist, see below), `SlicerVirtualReality_R\inner-build`, `SlicerVirtualReality_R`, `SlicerVirtualReality_R\inner-build\bin\Release`.

![image](https://github.com/KitwareMedical/SlicerVirtualReality/assets/1325980/5b5235b9-2077-4208-9ff1-7577c10e876e)

You can see in the error message that **a backslash is actually missing from the path**. The Close button obscures it a bit, but the path the error message suggests is `c:\d\_Extensions\SlicerVirtualReality_R\vtkRenderingOpenVR-buildvtk_openvr_actions.json` and not `c:\d\_Extensions\SlicerVirtualReality_R\vtkRenderingOpenVR-build\vtk_openvr_actions.json`.

When I copy the json to the incorrect path (without the backslash) it works!

Just to see the path the application stores I made the `actionManifestPath` function accessible in Python, and printed the value. It is the one it should be, if the missing backslash was added.
```
>>> vrvw.actionManifestPath()
'c:/d/_Extensions/SlicerVirtualReality_R/inner-build/lib/Slicer-5.3/../../../vtkRenderingOpenVR-build'
```

@jcfr Since you made this change, do you have any idea why the backshash could be removed? Thanks!

**Comment by LucasGandel** [comment]
@cpinter Nice catch!
I don't think the backslash is removed, it never exists (see [here](https://github.com/KitwareMedical/SlicerVirtualReality/commit/dec1acf0ceb08d15a6646f701442be9e4ea62bb7#diff-0cfd1cc8898274ead5d69b3b2b67c5b0f935c5c1ff1cab111a2a978c15d049c1R163) or in your vrvw.actionManifestPath() output).
VTK won't add the backslash for you (see [here](https://gitlab.kitware.com/vtk/vtk/-/blob/master/Rendering/OpenXR/vtkOpenXRRenderWindowInteractor.cxx?ref_type=heads#L533)), and it looks like all the VTK tests are using a trailing backslash when specifying this path.
So I guess the easy fix is just to add a trailing backslash to the path defined in SlicerVirtualReality. In the long term, VTK should be fixed to prevent the issue to happen again

**Comment by AkinaChinami** [comment]
We've installed the nightly build of Slicer (5.3.0-2023-06-10) and still have the manifest problem.
We've copied them:
- in the Extension folder: `[INSTALL_PATH]\slicer.org\Slicer 5.3.0-2023-06-10\slicer.org\Extensions-31787\`, but the manifests are not detected.
- in the "bin" folder which is requested on the error message when SlicerVR is launched: `[INSTALL_PATH]\slicer.org\Slicer 5.3.0-2023-06-10\slicer.org\Extensions-31787\bin\`, but the manifests are not detected. We created this folder in the "Extension" folder, as it didn't exist before.
- in the "bin" folder in the "SlicerVirtualReality" extension: `[INSTALL_PATH]\slicer.org\Slicer 5.3.0-2023-06-10\slicer.org\Extensions-31787\SlicerVirtualReality\bin`, but the manifests are not detected.

We've also tried renaming the json files in the same way as the error message displayed in SlicerVR but this doesn't work either, another error message has appeared: 
![image](https://github.com/KitwareMedical/SlicerVirtualReality/assets/59034831/cd26e654-13c9-4e8e-9df3-93abbfa3bc05)

What did you do to solve the problem?

**Comment by cpinter** [comment]
> Failed to load input bindings

I have never seen this error message. Does anyone has any idea? Does this mean that there is no appropriate json for the device? Or that the file has been corrupted?

About the nightly, I just tried it and the backslash problem is not fixed in that, see

![image](https://github.com/KitwareMedical/SlicerVirtualReality/assets/1325980/a379af72-56ca-4262-baf9-8937144fe14e)

I have the feeling that it is not the latest SlicerVR that is installed for the nightly. However, when I look at the ExtensionsIndex, I see that Slicer should always build the latest revision for the nightlies, see https://github.com/Slicer/ExtensionsIndex/blob/main/SlicerVirtualReality.s4ext#L10
The nightly extension build seems to have succeeded too: https://slicer.cdash.org/build/3059205
The revision in `ExtensionsMetadataFromServer.json` in the install matches the very latest commit, which is what we want.
Still, the slash is not there unfortunately.

To work around this for now: the path that works for the main json manifest file is `d:\Utils\Slicer 5.3.0-2023-06-12\slicer.org\Extensions-31791\binvtk_openvr_actions.json`, as seen in the screenshot above (I simplified the install path because the long path is cut off in the error window).
